### PR TITLE
Instagram support

### PR DESCRIPTION
**Pull request by karpawich**
This PR makes Sources better - particularly CrowdTangle ones. The overall changes are itemized below, and will be checked off as they are implemented:

- [x] Sources using CrowdTangle can now pull from **multiple Dashboards**.
- [x] Instagram is now a Source via CrowdTangle (with Reddit right around the corner if we want it!)
- [ ] ~~CrowdTangle-based Sources can now choose to pull from the whole platform using the `/posts/search` API~~
- [ ] ~~Twitter Sources can now choose to pull from specific [Twitter Lists](https://help.twitter.com/en/using-twitter/twitter-lists), similar to CrowdTangle Sources.~~

The crossed-out checklist items are no longer going to be implemented directly in Aggie because they will be made obsolete by the possible integration of [downstream](https://github.com/TID-Lab/downstream) in the future.

### CODE REVIEW

**Comment by karpawich** [comment]
**Note: This PR changes how CrowdTangle dashboard tokens are entered into Aggie.**

Tokens are no longer entered in to the `config/secrets.json`, but entered in via CrowdTangle Source settings instead.

**Comment by akjadhav** [comment]
Reviewed, no big errors/problems jump out at me

**Comment by akjadhav** [comment]
locale-es.json not updated, while locale-en.json is. Do we not need to?

**Comment by karpawich** [comment]
@akjadhav We haven't been, typically.

**Pull request merged**
