### PR TITLE
Substitute old `fetching` architecture with Downstream

### PR DESCRIPTION
**Pull request by karpawich**
**This PR is ready for review!**

### CODE REVIEW

**Comment by ciabhanconnelly** [comment]
I've fiddled with it for a mintue. Broke my own instance of Aggie trying to tweak/understand the code but everything seems to work great to me!

**Review by scottagt — APPROVED** [review]
I took a look and without spending some additional time trying it out for myself I can generally say the code looks good to go. The use of unit tests and automated continuous integration building can be another set of tools to catch potential issues in addition to PR reviews.

**Review by amehta265 — APPROVED** [review]
-All the back-end looks good. It is much simpler to read the code and follow through. 
- Credentials, fetching, use of hooks, downstream methods, controllers, models, hashing, all look good and make sense. 
- Unable to review most front-end (angular) changes.

**Review by akjadhav — APPROVED** [review]
Everything looks good to me. I don't see anything that can break Aggie.

**Review by limmabean — APPROVED** [review]
Works on my system and I don't see anything heinous that would break anything.

**Pull request merged**
